# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6df9417a3b72c3a840926d3a6abb86aa2cb32d80c1f32610f275358f097f2077f8541eff865dfb24bcf5681841a06da003fcbfd4c7905e2b24d7a04c8f66b218

test:
  secret_key_base: e7f5d910c5bc991378354fa5128a7a6da6e04533e4f7e7d50ed2cf5090670c54cfdec04037bcbc06613430df97b2d8b9018207be267215d7883b53f82012cd36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
